version: "3"

services:
  redis:
    image: "redis"
    ports:
      - 6379:6379

  movens-server:
    environment:
      - REDIS_PORT=6379
      - PORT=8080
    ports:
      - 80:8080
    links:
      - redis
