version: "3.7"

services:
    movens-server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: .env.local
        ports:
            - 8080:8080
        volumes:
            - ./src:/usr/node/app/src
            - ./nodemon.json:/usr/node/app/nodemon.json
    redis:
        image: redis
