version: "3.7"

services:
    redis:
        container_name: redis
        image: redis
        restart: always
    movens-server:
        container_name: movens-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: .env.local
        ports:
            - 8080:8080
        volumes:
            - ./src:/usr/node/app/src
            - ./nodemon.json:/usr/node/app/nodemon.json
