version: "3"

services:
  redis:
    image: "redis"
    logging:
      driver: awslogs
      options:
        awslogs-group: movens
        awslogs-region: eu-west-2
        awslogs-stream-prefix: redis

  movens-server:
    image: "551066471214.dkr.ecr.eu-west-2.amazonaws.com/movens-server"
    logging:
      driver: awslogs
      options:
        awslogs-group: movens
        awslogs-region: eu-west-2
        awslogs-stream-prefix: movens-server
