version: "3.7"

services:
    redis:
        image: redis
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
    movens-server:
        container_name: movens-server
        image: 551066471214.dkr.ecr.eu-west-2.amazonaws.com/movens-server
        environment:
            - REDIS_PORT=6379
        external_links:
            - redis
        depends_on:
            - redis
