version: "3.7"

services:
    redis:
        container_name: redis
        image: redis
        restart: always
    movens-server:
        container_name: movens-server
        restart: always
        build: .
        environment:
            - PORT=${PORT}
        ports:
            - 4000:${PORT}
