version: "3.7"

services:
    redis:
        restart: always
    movens-server_1:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
    movens-server_2:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        # volumes:
        #     - ./src:/usr/node/app/src
        #     - ./nodemon.json:/usr/node/app/nodemon.json
